version: '3'
services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    user: app
    volumes:
      - ./apps/:/app/apps
      - ./packages/:/app/packages
      - ./bin/:/app/bin
      - ./package.json:/app/package.json
      - ./.env:/app/.env
    networks:
      - app-network
  loadtest:
    image: loadtest
    build:
      context: .
      dockerfile: Dockerfile
    user: app
    env_file:
      - .env
    volumes:
      - ./apps/:/app/apps
      - ./packages/:/app/packages
      - ./bin/:/app/bin
      - ./package.json:/app/package.json
      - ./.env:/app/.env
    command: yarn workspace@app/condo cypress:loadtest
    networks:
      - app-network
  postgresdb:
    image: postgres:13.2
    command: postgres -c 'max_connections=2000'
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    networks:
      - app-network
  redis:
    image: redis:6.2
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - app-network
  dd-agent:
    image: "gcr.io/datadoghq/agent:7.40.0"
    cgroup_parent: host
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "127.0.0.1:8125:8125/udp"
      - "127.0.0.1:5002:5002"
      - "127.0.0.1:5555:5555"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"

networks:
  app-network:
    driver: bridge
