name: RUN CONDO TESTS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_FULL: swr.ru-moscow-1.hc.sbercloud.ru/condo/condo-tests-image/${{ github.sha }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_IMAGE_FULL: ${{ env.DOCKER_IMAGE_FULL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.SSH_DOCK_SERVER_PRIVATE_KEY }}
      
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: login to sbercloud registry
        uses: docker/login-action@v3
        with:
          registry: swr.ru-moscow-1.hc.sbercloud.ru
          username: ${{ secrets.SBERCLOUD_CR_USERNAME }}
          password: ${{ secrets.SBERCLOUD_CR_PASSWORD }}
      
      - name: build condo image for tests and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: condo.tests.Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE_FULL }}

  domains-tests-job:
    needs: build-image
    strategy:
      fail-fast: false  # for debug
      matrix:
        domain:
          - organization
          - user
          - scope
          - property
          - acquiring
          - billing
          - miniapp
          - banking
          - ticket
          - meter
          - contact
          - resident
          - notification
          - common
          - others
    uses: ./.github/workflows/_nodejs.condo.core.tests.yml
    with:
      domain_name: ${{ matrix.domain }}
      image: ${{ needs.build-image.outputs.DOCKER_IMAGE_FULL }}
    secrets: inherit